"""init

Revision ID: c4b951ce4b39
Revises: c8efbd7bc2bb
Create Date: 2021-07-29 00:11:19.710052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b951ce4b39'
down_revision = 'c8efbd7bc2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
