"""init

Revision ID: c8efbd7bc2bb
Revises: 31f5c98f7713
Create Date: 2021-07-29 00:05:16.272741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8efbd7bc2bb'
down_revision = '31f5c98f7713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
